import { FatalError } from "workflow"
import { generateText } from "ai"
import { createGateway } from "@ai-sdk/gateway"
import { google } from "@ai-sdk/google"
import { uploadImageToBlob } from "@/lib/blob-storage"
import { trackImageGeneration } from "@/lib/db/queries"
import type { GatewayMetadata } from "@/lib/ai-gateway"
import type { ModelType, ThinkingLevel, Resolution } from "@/components/image-combiner/types"

export interface GenerateImageInput {
  mode: "text-to-image" | "image-editing"
  prompt: string
  aspectRatio: string
  selectedModel: ModelType
  thinkingLevel: ThinkingLevel
  resolution: Resolution
  useGrounding: boolean
  apiKey: string
  userEmail: string | null
  ip: string
  // For image-editing mode, images are passed as data URLs
  image1DataUrl?: string
  image2DataUrl?: string
}

export interface GenerateImageResult {
  url: string
  prompt: string
  description: string
  durationMs: number
}

// --- Step functions (full Node.js access, auto-retry) ---
// google.tools.googleSearch() MUST be called inside steps, not in the workflow sandbox

async function executeTextToImage(input: {
  apiKey: string
  modelId: string
  prompt: string
  googleOptions: Record<string, any>
  useGrounding: boolean
}): Promise<{ base64: string; mediaType: string; text: string; totalTokens: number; providerMetadata: any; startedAt: number }> {
  "use step"

  const startedAt = Date.now()
  const gateway = createGateway({ apiKey: input.apiKey })
  const model = gateway(input.modelId)

  const imageGenerationPrompt = `Generate a high-quality image based on this description: ${input.prompt}. The image should be visually appealing and match the description as closely as possible.`

  // Build grounding tools inside the step (npm packages available here)
  const groundingTools = input.useGrounding
    ? { google_search: google.tools.googleSearch({ mode: "MODE_DYNAMIC" }) }
    : undefined

  const result = await generateText({
    model,
    prompt: imageGenerationPrompt,
    ...(groundingTools ? { tools: groundingTools } : {}),
    providerOptions: {
      google: input.googleOptions,
    },
  })

  const imageFiles = result.files?.filter((f) => f.mediaType?.startsWith("image/")) || []
  if (imageFiles.length === 0) {
    throw new FatalError("No image generated by the model")
  }

  return {
    base64: imageFiles[0].base64,
    mediaType: imageFiles[0].mediaType || "image/png",
    text: result.text || "",
    totalTokens: result.usage?.totalTokens || 0,
    providerMetadata: result.providerMetadata,
    startedAt,
  }
}

async function executeImageEditing(input: {
  apiKey: string
  modelId: string
  prompt: string
  image1DataUrl: string
  image2DataUrl: string | undefined
  googleOptions: Record<string, any>
  useGrounding: boolean
}): Promise<{ base64: string; mediaType: string; text: string; totalTokens: number; providerMetadata: any; startedAt: number }> {
  "use step"

  const startedAt = Date.now()
  const gateway = createGateway({ apiKey: input.apiKey })
  const model = gateway(input.modelId)

  const messageParts: Array<{ type: "text" | "image"; text?: string; image?: string }> = []
  messageParts.push({ type: "image", image: input.image1DataUrl })
  if (input.image2DataUrl) {
    messageParts.push({ type: "image", image: input.image2DataUrl })
  }

  const editingPrompt = input.image2DataUrl
    ? `${input.prompt}. Combine these two images creatively while following the instructions.`
    : `${input.prompt}. Edit or transform this image based on the instructions.`

  messageParts.push({ type: "text", text: editingPrompt })

  // Build grounding tools inside the step (npm packages available here)
  const groundingTools = input.useGrounding
    ? { google_search: google.tools.googleSearch({ mode: "MODE_DYNAMIC" }) }
    : undefined

  const result = await generateText({
    model,
    messages: [
      {
        role: "user",
        // @ts-ignore
        content: messageParts,
      },
    ],
    ...(groundingTools ? { tools: groundingTools } : {}),
    providerOptions: {
      google: input.googleOptions,
    },
  })

  const imageFiles = result.files?.filter((f) => f.mediaType?.startsWith("image/")) || []
  if (imageFiles.length === 0) {
    throw new FatalError("No image generated by the model")
  }

  return {
    base64: imageFiles[0].base64,
    mediaType: imageFiles[0].mediaType || "image/png",
    text: result.text || "",
    totalTokens: result.usage?.totalTokens || 0,
    providerMetadata: result.providerMetadata,
    startedAt,
  }
}

async function uploadToBlob(input: {
  base64: string
  mediaType: string
  mode: string
}): Promise<string> {
  "use step"

  const imageUrl = `data:${input.mediaType};base64,${input.base64}`
  const prefix = input.mode === "text-to-image" ? "generation" : "editing"
  const filename = `${prefix}-${Date.now()}-${Math.random().toString(36).substring(7)}.png`

  // Let errors propagate so the step retries automatically
  return await uploadImageToBlob(imageUrl, filename)
}

async function trackGeneration(input: {
  userEmail: string | null
  providerMetadata: any
  totalTokens: number
  metadata: Record<string, any>
}): Promise<void> {
  "use step"

  const gatewayMeta = input.providerMetadata?.gateway as unknown as GatewayMetadata
  const cost = gatewayMeta?.cost || "0"

  await trackImageGeneration({
    userEmail: input.userEmail,
    cost,
    tokens: input.totalTokens,
    metadata: input.metadata,
  })
}

// --- Main workflow function ---
// IMPORTANT: No npm package calls here — only orchestration of steps.
// Date.now() is seeded/deterministic in the sandbox, so use step-returned timestamps.

export async function generateImageWorkflow(input: GenerateImageInput): Promise<GenerateImageResult> {
  "use workflow"

  // Build model config (pure data, no npm calls)
  const modelIdMap: Record<ModelType, string> = {
    nb2: "google/gemini-3.1-flash-image-preview",
    pro: "google/gemini-3-pro-image",
    classic: "google/gemini-2.5-flash-image",
  }
  const modelNameMap: Record<ModelType, string> = {
    nb2: "NB2",
    pro: "Pro",
    classic: "Classic",
  }

  const modelId = modelIdMap[input.selectedModel] || modelIdMap.nb2
  const modelName = modelNameMap[input.selectedModel] || "NB2"

  const geminiAspectRatioMap: Record<string, string> = {
    portrait: "9:16",
    landscape: "16:9",
    wide: "21:9",
    "4:3": "4:3",
    "3:4": "3:4",
    "3:2": "3:2",
    "2:3": "2:3",
    "5:4": "5:4",
    "4:5": "4:5",
    square: "1:1",
  }
  const geminiAspectRatio = geminiAspectRatioMap[input.aspectRatio] || "1:1"

  const googleOptions: Record<string, any> = {
    responseModalities: ["IMAGE"],
    imageConfig: { aspectRatio: geminiAspectRatio },
  }

  if (input.selectedModel === "nb2" && input.thinkingLevel === "high") {
    googleOptions.thinkingConfig = { thinkingLevel: "high" }
  }

  if (input.selectedModel === "nb2" && input.resolution !== "1K") {
    googleOptions.imageConfig.imageSize = input.resolution
  }

  // Step 1: Generate the image (grounding tools built inside the step)
  let genResult
  if (input.mode === "text-to-image") {
    genResult = await executeTextToImage({
      apiKey: input.apiKey,
      modelId,
      prompt: input.prompt,
      googleOptions,
      useGrounding: input.selectedModel === "nb2" && input.useGrounding,
    })
  } else {
    genResult = await executeImageEditing({
      apiKey: input.apiKey,
      modelId,
      prompt: input.prompt,
      image1DataUrl: input.image1DataUrl!,
      image2DataUrl: input.image2DataUrl,
      googleOptions,
      useGrounding: input.selectedModel === "nb2" && input.useGrounding,
    })
  }

  // Step 2: Upload to blob storage
  const blobUrl = await uploadToBlob({
    base64: genResult.base64,
    mediaType: genResult.mediaType,
    mode: input.mode,
  })

  // Compute duration using real wall-clock time from the step
  const durationMs = Date.now() - genResult.startedAt

  // Step 3: Track the generation (errors propagate for retry)
  await trackGeneration({
    userEmail: input.userEmail,
    providerMetadata: genResult.providerMetadata,
    totalTokens: genResult.totalTokens,
    metadata: {
      mode: input.mode,
      prompt: input.prompt,
      aspectRatio: input.aspectRatio,
      model: modelName,
      selectedModel: input.selectedModel,
      thinkingLevel: input.selectedModel === "nb2" ? input.thinkingLevel : undefined,
      resolution: input.selectedModel === "nb2" ? input.resolution : undefined,
      useGrounding: input.selectedModel === "nb2" ? input.useGrounding : undefined,
      ip: input.ip,
      durationMs,
    },
  })

  return {
    url: blobUrl,
    prompt: input.prompt,
    description: genResult.text,
    durationMs,
  }
}
